[tool.poetry]
name = "graphlet"
version = "0.1.0"
description = "Graphlet AI Knowledge Graph Factory"
authors = ["Russell Jurney <rjurney@graphlet.ai>"]

[tool.poetry.dependencies]
python = "^3.9"
pyspark = "^3.2.1"
pydantic = "^1.9.1"
pydantic-spark = "^0.1.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
target-version = ['py310']
include = ['graphlet', 'tests']
exclude = []

[tool.isort]
profile = "black"
src_paths = ["graphlet", "test"]
